"""add quantity to sub_items

Revision ID: 70fe9300041c
Revises: 7e136207dc26
Create Date: 2026-05-06 13:05:11.337190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70fe9300041c'
down_revision: Union[str, Sequence[str], None] = '7e136207dc26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sub_items', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_items', 'quantity')
    # ### end Alembic commands ###
